name: acw_battle_data
dependencies:
- alabaster=0.7.6=py35_0
- anaconda-client=1.2.1=py35_0
- babel=2.1.1=py35_0
- clyent=1.2.0=py35_0
- docutils=0.12=py35_0
- jinja2=2.8=py35_0
- libxml2=2.9.2=0
- libxslt=1.1.28=2
- lxml=3.5.0=py35_0
- markupsafe=0.23=py35_0
- numexpr=2.4.4=np110py35_0
- numpy=1.10.2=py35_0
- openssl=1.0.2d=0
- pandas=0.17.1=np110py35_0
- pip=7.1.2=py35_0
- pygments=2.0.2=py35_0
- pyparsing=2.0.3=py35_0
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- pyyaml=3.11=py35_1
- readline=6.2=2
- requests=2.9.0=py35_0
- setuptools=19.1.1=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.0=py35_0
- sphinx=1.3.1=py35_0
- sphinx_rtd_theme=0.1.7=py35_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - awscli==1.9.15
  - botocore==1.3.15
  - colorama==0.3.3
  - isodate==0.5.4
  - jmespath==0.9.0
  - keepalive==0.5
  - nameparser==0.3.11
  - pyasn1==0.1.9
  - rdflib==4.2.1
  - rsa==3.2.3
  - sparqlwrapper==1.7.6
  - sphinx-rtd-theme==0.1.7
  - tabulate==0.7.5

