name: acw_battle_data
dependencies:
- alabaster
- anaconda-client
- babel
- clyent
- docutils
- imagesize
- jinja2
- libxml2
- libxslt
- lxml
- markupsafe
- mkl
- numexpr
- numpy
- openssl
- pandas
- pip
- pygments
- pyparsing
- python>=3.5
- python-dateutil
- pytz
- pyyaml
- readline
- requests
- setuptools
- six
- snowballstemmer
- sphinx
- sphinx_rtd_theme
- sqlite
- tk
- wheel
- xz
- yaml
- zlib
- pip:
  - awscli
  - botocore
  - colorama
  - isodate
  - jmespath
  - keepalive
  - nameparser
  - pyasn1
  - rdflib
  - rsa
  - sparqlwrapper
  - sphinx-rtd-theme
  - tabulate
