Bodart1908:
  name: >-
    Bodart, Gaston, 1908. *Militär-historisches kreigs-lexikon, (1618-1905)*
  url: http://books.google.com/books?id=Eo4DAAAAYAAJ .
CWSAC1993b:
  name: >-
    Staff of the Civil War Sites Advisory Commission (CWSAC), 1993 *Civil War Sites Advisory Commission Report on the Nation's Civil War Battlefields: Technical Volume II: Battle Summaries*

  url: http://www.nps.gov/abpp/battles/tvii.htm

CWSAC1993a:
  name: >-
    Staff of the Civil War Sites Advisory Commission (CWSAC), 1993 *Civil War Sites Advisory Commission Report on the Nation's Civil War Battlefields*

  url: http://www.nps.gov/abpp/cwsac/cws0-1.html

CWAC2012:
  name: >-
    U.S. Department of the Interior, National Park Service, "State by State Updates to the Civil War Sites Advisory Commission Report"
  url: http://www.nps.gov/abpp/CWSII/CWSIIStateReports.htm

Shenandoah1992:
  name: U.S. Department of the Interior, National Park Service, 1992. "Study of Civil War Sites in the Shenandoah Valley of Virginia"
  url: http://www.nps.gov/abpp/shenandoah/svs0-1.html



  



    
  