ACAA1994:
  text: U.S. Army Concepts Analysis Agency. 1994. “PAR Datadisk (personnel Attrition Rates in Historical Land Combat Operations) (revised) Version 2.1 (computer Diskette).” http://oai.dtic.mil/oai/oai?verb=getRecord&metadataPrefix=html&identifier=ADM000368.
  url: http://oai.dtic.mil/oai/oai?verb=getRecord&metadataPrefix=html&identifier=ADM000368
Bodart1908:
  text: Bodart, Gaston. 1908. Militär-Historisches Kreigs-Lexikon, (1618-1905). Stern. http://books.google.com/books?id=Eo4DAAAAYAAJ.
  url: http://books.google.com/books?id=Eo4DAAAAYAAJ
BurdekinLangdana1993:
  text: 'Burdekin, Richard C. K., and Farrokh K. Langdana. 1993. “War Finance in the Southern Confederacy, 1861-1865.” Explorations in Economic History 30(3): 352 – 376. http://www.sciencedirect.com/science/article/B6WFJ-45PMM8X-D/2/0332a9f88be4f3e45940cc43f8263a42.'
  url: http://www.sciencedirect.com/science/article/B6WFJ-45PMM8X-D/2/0332a9f88be4f3e45940cc43f8263a42
CWSAC1993:
  text: Staff of the Civil War Sites Advisory Commission. 1993. Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields. http://www.nps.gov/abpp/cwsac/cws0-1.html (December 7, 2015).
  url: http://www.nps.gov/abpp/cwsac/cws0-1.html
CWSAC1997:
  text: 'Staff of the Civil War Sites Advisory Commission. 1997. Report on the Nation’s Civil War Battlefields: Technical Volume iI: Battle Summaries. http://www.nps.gov/abpp/battles/tvii.htm (December 7, 2015).'
  url: http://www.nps.gov/abpp/battles/tvii.htm
CWSAC_AAD:
  text: Civil War Sites Advisory Commission. Records About Civil War Battle Sites, Created, 1990 - 1993, Documenting the Period 4/12/1861 - 5/13/1865. ed. The National Archives. Data Files ; Textual Records. https://aad.archives.gov/aad/series-description.jsp?s=1076&cat=WR25&bc=,sl (December 7, 2015).
  url: https://aad.archives.gov/aad/series-description.jsp?s=1076&cat=WR25&bc=,sl
CWSAC_by_campgn:
  text: 'National Park Service. “CWSAC Battle Summaries: Civil War Battle Summaries by Campaign.” http://www.nps.gov/abpp/battles/bycampgn.htm (December 7, 2015).'
  url: http://www.nps.gov/abpp/battles/bycampgn.htm
CWSAC_by_state:
  text: 'National Park Service. “CWSAC Battle Summaries: Civil War Battle Summaries by State.” http://www.nps.gov/abpp/battles/bystate.htm (December 7, 2015).'
  url: http://www.nps.gov/abpp/battles/bystate.htm
CWSII:
  text: National Park Service. 2012. “Civil War Sites Advistory Commission Report Update & Resurvey.” http://www.nps.gov/hps/abpp/CWSII/CWSII.htm (December 7, 2015).
  url: http://www.nps.gov/hps/abpp/CWSII/CWSII.htm
CWSIIAL:
  text: 'National Park Service. 2011. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of Alabama. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportAlabamaUpdate.pdf.'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportAlabamaUpdate.pdf
CWSIIAR:
  text: 'National Park Service. 2010. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of Arkansas. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportArkansasUpdate.pdf.'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportArkansasUpdate.pdf
CWSIICO:
  text: 'National Park Service. 2010. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: For Western Battlefields: States of Colorado, Idaho, and New Mexico. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportFarWestUpdate.pdf.'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportFarWestUpdate.pdf
CWSIIDC:
  text: 'National Park Service. 2009. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: District of Columbia. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportWashingtonDCUpdate.pdf.'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportWashingtonDCUpdate.pdf
CWSIIFL:
  text: 'National Park Service. 2011. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of Florida. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportFloridaUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportFloridaUpdate.pdf
CWSIIGA:
  text: 'National Park Service. 2010. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of Georgia. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportGeorgiaUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportGeorgiaUpdate.pdf
CWSIIIN:
  text: 'National Park Service. 2009. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of Indiana. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportIndianaUpdatewithCover.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportIndianaUpdatewithCover.pdf
CWSIIKS:
  text: 'National Park Service. 2010. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of Kansas. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportKansasUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportKansasUpdate.pdf
CWSIIKY:
  text: 'National Park Service. 2009. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of Kentucky. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportKentuckyUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportKentuckyUpdate.pdf
CWSIILA:
  text: 'National Park Service. 2010. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of Louisiana. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportLouisianaUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportLouisianaUpdate.pdf
CWSIIMD:
  text: 'National Park Service. 2010. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of Maryland. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportMarylandUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportMarylandUpdate.pdf
CWSIIMN:
  text: 'National Park Service. 2010. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of Minnesota. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportMinnesotaUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportMinnesotaUpdate.pdf
CWSIIMO:
  text: 'National Park Service. 2011. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of Missouri. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportMissouriUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportMissouriUpdate.pdf
CWSIINC:
  text: 'National Park Service. 2010. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of North Carolina. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportNorthCarolinaUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportNorthCarolinaUpdate.pdf
CWSIIND:
  text: 'National Park Service. 2010. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of North Dakoa. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportNorthDakotaUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportNorthDakotaUpdate.pdf
CWSIIOH:
  text: 'National Park Service. 2009. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of Ohio. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportOhioUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportOhioUpdate.pdf
CWSIIOK:
  text: 'National Park Service. 2010. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of Oklahoma. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportOklahomaUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportOklahomaUpdate.pdf
CWSIIPA:
  text: 'National Park Service. 2010. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: Commonwealth of Pennsylvania. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportPennsylvaniaUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportPennsylvaniaUpdate.pdf
CWSIISC:
  text: 'National Park Service. 2010. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of South Carolina. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportSouthCarolinaUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportSouthCarolinaUpdate.pdf
CWSIITN:
  text: 'National Park Service. 2009. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of Tennessee. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportTennesseeUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportTennesseeUpdate.pdf
CWSIITX:
  text: 'National Park Service. 2010. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of Texas. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportTexasUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportTexasUpdate.pdf
CWSIIVA:
  text: 'National Park Service. 2009. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: Commonwealth of Virginia. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportVirginiaUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportVirginiaUpdate.pdf
CWSIIWV:
  text: 'National Park Service. 2010. Update to the Civil War Sites Advisory Commission Report on the Nation’s Civil War Battlefields: State of West Virginia. Washington, D.C. http://www.nps.gov/abpp/CWSII/CWSACReportWestVirginiaUpdate.pdf (December 7, 2015).'
  url: http://www.nps.gov/abpp/CWSII/CWSACReportWestVirginiaUpdate.pdf
CWSS:
  text: National Park Service. “Civil War Soldiers and Sailors Database (cWSS).” http://www.nps.gov/civilwar/soldiers-and-sailors-database.htm (December 7, 2015).
  url: http://www.nps.gov/civilwar/soldiers-and-sailors-database.htm
Clodfelter2008:
  text: 'Clodfelter, Michael. 2008. Warfare and Armed Conflicts: A Statistical Encyclopedia of Casualty and Other Figures, 1494- 2007. 3rd ed. McFarland & Company.'
  url: null
DyerBattles:
  text: 'Dyer, Frederick H. “Compendium of the War of the Rebellion: Battles” ed. Perseus Digital Library. http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2001.05.0140.'
  url: http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2001.05.0140
Eicher2001:
  text: 'Eicher, David J. 2001. The Longest Night: A Military History of the Civil War. ed. James M. McPherson. Simon & Schuster. http://books.google.com/books?id=1p94XzYASDAC.'
  url: http://books.google.com/books?id=1p94XzYASDAC
Greer2005:
  text: Greer, Darroch. 2005. “Counting Civil War Casualties, Week-by-Week, for the Abraham Lincoln Presidential Library and Museum.” http://www.brcweb.com/alplm/BRC_Counting_Casualties.pdf.
  url: http://www.brcweb.com/alplm/BRC_Counting_Casualties.pdf
Helmbold1993:
  text: 'Helmbold, Robert L. 1993. Personnel Attrition Rates in Historical Land Combat Operations: An Annotated Bibliography. U.S. Army Concepts Analysis Agency. Research Paper. http://handle.dtic.mil/100.2/ADA268787.'
  url: http://handle.dtic.mil/100.2/ADA268787
Helmbold1993b:
  text: 'Helmbold, Robert L. 1993. Personnel Attrition Rates in Historical Land Combat Operations: A Catalog of Attrition and Casualty Data Bases on Diskettes Usable with Personal Computers. U.S. Army Concepts Analysis Agency. Research Paper. http://handle.dtic.mil/100.2/ADA279069.'
  url: http://handle.dtic.mil/100.2/ADA279069
KennedyConservation1998:
  text: Kennedy, Frances H., Conservation Fund (Arlington, Va.). 1998. The Civil War Battlefield Guide. Houghton Mifflin. http://books.google.com/books?id=qHObJArDHZMC.
  url: http://books.google.com/books?id=qHObJArDHZMC
Livermore1900:
  text: Livermore, Thomas Leonard. 1900. Number and Losses in the Civil War in America, 1861-65. Houghton, Mifflin; Company. http://books.google.com/books?id=Qw8pAAAAYAAJ.
  url: http://books.google.com/books?id=Qw8pAAAAYAAJ
McPherson2003:
  text: 'McPherson, James M. 2003. Battle Cry of Freedom: The Civil War Era. Oxford University Press. http://books.google.com/books?id=GXfGuNAvm7AC.'
  url: http://books.google.com/books?id=GXfGuNAvm7AC
NPS1992:
  text: National Park Service. 1992. Study of Civil War Sites in the Shenandoah Valley of Virginia. http://www.nps.gov/abpp/shenandoah/svs0-1.html (December 7, 2015).
  url: http://www.nps.gov/abpp/shenandoah/svs0-1.html
NYT1861:
  text: “History of the Rebellion.; Chronological Record of the Leading Incidents of the War. Chronology of the War. Chronology of the Blockade.” 1861. New York Times. http://www.nytimes.com/1861/12/31/news/history-rebellion-chronological-record-leading-incidents-war-chronology-war.html.
  url: http://www.nytimes.com/1861/12/31/news/history-rebellion-chronological-record-leading-incidents-war-chronology-war.html
NYT1862:
  text: “A Year of War.; Diary of Military and Naval Events of 1862. Victories and Defeats, Triumphs and Disasters, Successes and Reverses of the Army and Navy of the Union.” 1862. New York Times. http://www.nytimes.com/1862/12/31/news/year-war-diary-military-naval-events-1862-victories-defeats-triumphs-disasters.html.
  url: http://www.nytimes.com/1862/12/31/news/year-war-diary-military-naval-events-1862-victories-defeats-triumphs-disasters.html
NYT1863:
  text: “BATTLE rECORD fOR 1863.; Chronological Table of the Events of the Year. Our Victories and Defeats by Land and Sea. the Great Battles and Events of the Year.” 1863. New York Times. http://www.nytimes.com/1863/12/31/news/battle-record-for-1863-chronological-table-events-year-our-victories-defeats.html.
  url: http://www.nytimes.com/1863/12/31/news/battle-record-for-1863-chronological-table-events-year-our-victories-defeats.html
NYT1864:
  text: “1864.; Chronological Record of the Military, Naval and Political Events of the Year. a Year of Great Events, Great Battles, Great Triumphs and Great Results.” 1864. New York Times. http://www.nytimes.com/1864/12/31/news/1864-chronological-record-military-naval-political-events-year-year-great-events.html.
  url: http://www.nytimes.com/1864/12/31/news/1864-chronological-record-military-naval-political-events-year-year-great-events.html
NYT1865:
  text: “EVENTS iN 1865.; Chronicle of Noteworthy Occurrences for the Year. cLOSE oF tHE wAR fOR tHE uNION Miscellaneous Events at Home and Abroad.” 1865. New York Times.
  url: null
Phisterer1883:
  text: Phisterer, Frederick. 1883. Statistical Records of the Armies of the United States. C. Scribner’s Sons. http://books.google.com/books?id=cVNHr_nnLlYC.
  url: http://books.google.com/books?id=cVNHr_nnLlYC
Reiter2009:
  text: Reiter, Dan. 2009. How wars end. Princeton University Press. http://books.google.com/books?id=-_Avp1TNYjMC.
  url: http://books.google.com/books?id=-_Avp1TNYjMC
Schwab1901:
  text: 'Schwab, John Christopher. 1901. The Confederate States of America, 1861-1865: A Financial and Industrial History of the South During the Civil War. C. Scribner’s Sons. http://books.google.com/books?id=4TEOAAAAIAAJ.'
  url: http://books.google.com/books?id=4TEOAAAAIAAJ
Thorpe2011:
  text: Thorpe, Gene. 2011. “Battles and Casualties of the Civil War Map.” The Washington Post. http://www.washingtonpost.com/wp-srv/lifestyle/special/civil-war-interactive/civil-war-battles-and-casualties-interactive-map/ (December 7, 2015).
  url: http://www.washingtonpost.com/wp-srv/lifestyle/special/civil-war-interactive/civil-war-battles-and-casualties-interactive-map/
cdb90:
  text: U.S. Army Concepts Analysis Agency. 1991. “Database of Battles-Version 1990 (computer Diskette).” http://www.dtic.mil/docs/citations/ADM000121.
  url: http://www.dtic.mil/docs/citations/ADM000121
dyer1908_war_rebel:
  text: Dyer, F.H. 1908. A Compendium of the War of the Rebellion. The Dyer publishing company. http://books.google.com/books?id=OBkNAQAAMAAJ.
  url: http://books.google.com/books?id=OBkNAQAAMAAJ
eicher2002civil:
  text: Eicher, J., and D. Eicher. 2002. Civil War High Commands. Stanford University Press. https://books.google.com/books?id=Fs0Ajlnjl6AC.
  url: https://books.google.com/books?id=Fs0Ajlnjl6AC
fox1898regimental:
  text: Fox, William Freeman. 1898. Regimental Losses in the American Civil War, 1861-1865. A Treatise on the Extent and Nature of the Mortuary Losses in the Union Regiments, with Full and Exhaustive Statistics Compiled from the Official Records on File in the State Military Bureaus and at Washington. Albany Pub. Co. http://books.google.com/books?id=R5YukgAACAAJ.
  url: http://books.google.com/books?id=R5YukgAACAAJ
jrnold:
  email: jeffrey.arnold@gmail.com
  text: Jeffrey B. Arnold
civilwarorg:
  text: >-
    "Civil War Battlefields - Learn About The American Civil War." Civil War Trust: Saving America's Civil War Battlefields. Accessed December 24, 2015. 
  url: http://www.civilwar.org/battlefields/
